schedules:
- cron: "27 3 */1 * *"
  # 3:27am UTC everyday
  displayName: Nighthly build
  branches:
    include:
    - master
  always: true

trigger:
- master

pr:
- master

jobs:
  - template: azure/windows.yml
    parameters:
      name: windows
      vmImage: windows-2019
      matrix:
        py_3.7_32:
          PYTHON_VERSION: "3.7"
          PYTHON_ARCH: "x86"
          NP_BUILD_DEP: "1.17.3"
          # pandas 1.4 requires py3.8+, remove this job on 1.4 release
          NIGHTLY_BUILD: "false"
        py_3.7_64:
          PYTHON_VERSION: "3.7"
          PYTHON_ARCH: "x64"
          NP_BUILD_DEP: "1.17.3"
          # pandas 1.4 requires py3.8+, remove this job on 1.4 release
          NIGHTLY_BUILD: "false"
        py_3.8_32:
          PYTHON_VERSION: "3.8"
          PYTHON_ARCH: "x86"
          NP_BUILD_DEP: "1.17.3"
          NIGHTLY_BUILD: "true"
        py_3.8_64:
          PYTHON_VERSION: "3.8"
          PYTHON_ARCH: "x64"
          NP_BUILD_DEP: "1.17.3"
          NIGHTLY_BUILD: "true"
        py_3.9_32:
          PYTHON_VERSION: "3.9"
          PYTHON_ARCH: "x86"
          NP_BUILD_DEP: "1.19.3"
          NIGHTLY_BUILD: "true"
        py_3.9_64:
          PYTHON_VERSION: "3.9"
          PYTHON_ARCH: "x64"
          NP_BUILD_DEP: "1.19.3"
          NIGHTLY_BUILD: "true"

  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-latest
      matrix:
        py_3.7_32:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
          PLAT: "i686"
          NP_BUILD_DEP: "numpy==1.17.3"
          # pandas 1.4 requires py3.8+, remove this job on 1.4 release
          NIGHTLY_BUILD: "false"
        py_3.7_64:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
          NP_BUILD_DEP: "numpy==1.17.3"
          # pandas 1.4 requires py3.8+, remove this job on 1.4 release
          NIGHTLY_BUILD: "false"
        py_3.8_32:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          PLAT: "i686"
          NP_BUILD_DEP: "numpy==1.17.3"
          NIGHTLY_BUILD: "true"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          NP_BUILD_DEP: "numpy==1.17.3"
          NIGHTLY_BUILD: "true"
        py_3.9_32:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
          PLAT: "i686"
          NP_BUILD_DEP: "numpy==1.19.3"
          NIGHTLY_BUILD: "true"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
          NP_BUILD_DEP: "numpy==1.19.3"
          NIGHTLY_BUILD: "true"


  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.15
      matrix:
        py_3.7_64:
          MB_PYTHON_VERSION: "3.7"
          NP_BUILD_DEP: "numpy==1.17.3"
          # pandas 1.4 requires py3.8+, remove this job on 1.4 release
          NIGHTLY_BUILD: "false"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
          NP_BUILD_DEP: "numpy==1.17.3"
          NIGHTLY_BUILD: "true"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"
          NP_BUILD_DEP: "numpy==1.19.3"
          NIGHTLY_BUILD: "true"
   
  # Verify that the Windows builds are packaged with the correct dlls
  # Download a wheel from the nightlies and verify that it works
  - job: py37_verify_windows
    #condition: eq(variables['Build.Reason'], 'Schedule')
    pool:
      vmImage: windows-2019
    container: mcr.microsoft.com/windows/servercore:ltsc2019 # Use custom container without VS 2019
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.7"
          architecture: "x64"
        displayName: Set python version
      - script: |
          pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple pandas
          python -c "import pandas as pd; print('import successful')"
